import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

type Category = 'ANIMAL' | 'FOOD' | 'OBJECT' | 'NATURE' | 'PLACE' | 'ACTION' | 'JOB';

const words: { word: string; category: Category }[] = [
  // ANIMAL (50)
  { word: '강아지', category: 'ANIMAL' },
  { word: '고양이', category: 'ANIMAL' },
  { word: '호랑이', category: 'ANIMAL' },
  { word: '코끼리', category: 'ANIMAL' },
  { word: '펭귄', category: 'ANIMAL' },
  { word: '토끼', category: 'ANIMAL' },
  { word: '곰', category: 'ANIMAL' },
  { word: '사자', category: 'ANIMAL' },
  { word: '기린', category: 'ANIMAL' },
  { word: '원숭이', category: 'ANIMAL' },
  { word: '독수리', category: 'ANIMAL' },
  { word: '앵무새', category: 'ANIMAL' },
  { word: '돌고래', category: 'ANIMAL' },
  { word: '상어', category: 'ANIMAL' },
  { word: '고래', category: 'ANIMAL' },
  { word: '문어', category: 'ANIMAL' },
  { word: '거북이', category: 'ANIMAL' },
  { word: '개구리', category: 'ANIMAL' },
  { word: '뱀', category: 'ANIMAL' },
  { word: '악어', category: 'ANIMAL' },
  { word: '말', category: 'ANIMAL' },
  { word: '소', category: 'ANIMAL' },
  { word: '돼지', category: 'ANIMAL' },
  { word: '닭', category: 'ANIMAL' },
  { word: '오리', category: 'ANIMAL' },
  { word: '여우', category: 'ANIMAL' },
  { word: '늑대', category: 'ANIMAL' },
  { word: '곰팡이', category: 'ANIMAL' },
  { word: '하마', category: 'ANIMAL' },
  { word: '코뿔소', category: 'ANIMAL' },
  { word: '치타', category: 'ANIMAL' },
  { word: '표범', category: 'ANIMAL' },
  { word: '플라밍고', category: 'ANIMAL' },
  { word: '공작새', category: 'ANIMAL' },
  { word: '올빼미', category: 'ANIMAL' },
  { word: '참새', category: 'ANIMAL' },
  { word: '까마귀', category: 'ANIMAL' },
  { word: '제비', category: 'ANIMAL' },
  { word: '황새', category: 'ANIMAL' },
  { word: '두꺼비', category: 'ANIMAL' },
  { word: '도마뱀', category: 'ANIMAL' },
  { word: '카멜레온', category: 'ANIMAL' },
  { word: '고슴도치', category: 'ANIMAL' },
  { word: '다람쥐', category: 'ANIMAL' },
  { word: '너구리', category: 'ANIMAL' },
  { word: '오소리', category: 'ANIMAL' },
  { word: '수달', category: 'ANIMAL' },
  { word: '물개', category: 'ANIMAL' },
  { word: '북극곰', category: 'ANIMAL' },
  { word: '낙타', category: 'ANIMAL' },

  // FOOD (50)
  { word: '김밥', category: 'FOOD' },
  { word: '떡볶이', category: 'FOOD' },
  { word: '피자', category: 'FOOD' },
  { word: '바나나', category: 'FOOD' },
  { word: '라면', category: 'FOOD' },
  { word: '치킨', category: 'FOOD' },
  { word: '햄버거', category: 'FOOD' },
  { word: '수박', category: 'FOOD' },
  { word: '딸기', category: 'FOOD' },
  { word: '포도', category: 'FOOD' },
  { word: '사과', category: 'FOOD' },
  { word: '배', category: 'FOOD' },
  { word: '감자', category: 'FOOD' },
  { word: '고구마', category: 'FOOD' },
  { word: '당근', category: 'FOOD' },
  { word: '양파', category: 'FOOD' },
  { word: '브로콜리', category: 'FOOD' },
  { word: '삼겹살', category: 'FOOD' },
  { word: '불고기', category: 'FOOD' },
  { word: '순대', category: 'FOOD' },
  { word: '빵', category: 'FOOD' },
  { word: '케이크', category: 'FOOD' },
  { word: '아이스크림', category: 'FOOD' },
  { word: '초콜릿', category: 'FOOD' },
  { word: '커피', category: 'FOOD' },
  { word: '주스', category: 'FOOD' },
  { word: '우유', category: 'FOOD' },
  { word: '달걀', category: 'FOOD' },
  { word: '두부', category: 'FOOD' },
  { word: '된장찌개', category: 'FOOD' },
  { word: '김치찌개', category: 'FOOD' },
  { word: '비빔밥', category: 'FOOD' },
  { word: '냉면', category: 'FOOD' },
  { word: '갈비', category: 'FOOD' },
  { word: '스테이크', category: 'FOOD' },
  { word: '파스타', category: 'FOOD' },
  { word: '스시', category: 'FOOD' },
  { word: '타코', category: 'FOOD' },
  { word: '샌드위치', category: 'FOOD' },
  { word: '샐러드', category: 'FOOD' },
  { word: '오렌지', category: 'FOOD' },
  { word: '레몬', category: 'FOOD' },
  { word: '망고', category: 'FOOD' },
  { word: '파인애플', category: 'FOOD' },
  { word: '키위', category: 'FOOD' },
  { word: '복숭아', category: 'FOOD' },
  { word: '자두', category: 'FOOD' },
  { word: '체리', category: 'FOOD' },
  { word: '블루베리', category: 'FOOD' },
  { word: '옥수수', category: 'FOOD' },

  // OBJECT (50)
  { word: '우산', category: 'OBJECT' },
  { word: '가위', category: 'OBJECT' },
  { word: '시계', category: 'OBJECT' },
  { word: '의자', category: 'OBJECT' },
  { word: '칫솔', category: 'OBJECT' },
  { word: '책', category: 'OBJECT' },
  { word: '연필', category: 'OBJECT' },
  { word: '지우개', category: 'OBJECT' },
  { word: '안경', category: 'OBJECT' },
  { word: '전화기', category: 'OBJECT' },
  { word: '컴퓨터', category: 'OBJECT' },
  { word: '키보드', category: 'OBJECT' },
  { word: '마우스', category: 'OBJECT' },
  { word: '카메라', category: 'OBJECT' },
  { word: '가방', category: 'OBJECT' },
  { word: '지갑', category: 'OBJECT' },
  { word: '열쇠', category: 'OBJECT' },
  { word: '자전거', category: 'OBJECT' },
  { word: '자동차', category: 'OBJECT' },
  { word: '버스', category: 'OBJECT' },
  { word: '기차', category: 'OBJECT' },
  { word: '비행기', category: 'OBJECT' },
  { word: '배', category: 'OBJECT' },
  { word: '신발', category: 'OBJECT' },
  { word: '모자', category: 'OBJECT' },
  { word: '장갑', category: 'OBJECT' },
  { word: '목도리', category: 'OBJECT' },
  { word: '텔레비전', category: 'OBJECT' },
  { word: '냉장고', category: 'OBJECT' },
  { word: '세탁기', category: 'OBJECT' },
  { word: '전자레인지', category: 'OBJECT' },
  { word: '선풍기', category: 'OBJECT' },
  { word: '에어컨', category: 'OBJECT' },
  { word: '침대', category: 'OBJECT' },
  { word: '책상', category: 'OBJECT' },
  { word: '소파', category: 'OBJECT' },
  { word: '거울', category: 'OBJECT' },
  { word: '빗', category: 'OBJECT' },
  { word: '비누', category: 'OBJECT' },
  { word: '샴푸', category: 'OBJECT' },
  { word: '수건', category: 'OBJECT' },
  { word: '양말', category: 'OBJECT' },
  { word: '바지', category: 'OBJECT' },
  { word: '셔츠', category: 'OBJECT' },
  { word: '드레스', category: 'OBJECT' },
  { word: '넥타이', category: 'OBJECT' },
  { word: '반지', category: 'OBJECT' },
  { word: '목걸이', category: 'OBJECT' },
  { word: '귀걸이', category: 'OBJECT' },
  { word: '시험지', category: 'OBJECT' },

  // NATURE (50)
  { word: '무지개', category: 'NATURE' },
  { word: '화산', category: 'NATURE' },
  { word: '폭포', category: 'NATURE' },
  { word: '단풍', category: 'NATURE' },
  { word: '눈사람', category: 'NATURE' },
  { word: '구름', category: 'NATURE' },
  { word: '번개', category: 'NATURE' },
  { word: '태풍', category: 'NATURE' },
  { word: '지진', category: 'NATURE' },
  { word: '해일', category: 'NATURE' },
  { word: '눈송이', category: 'NATURE' },
  { word: '빙하', category: 'NATURE' },
  { word: '사막', category: 'NATURE' },
  { word: '오아시스', category: 'NATURE' },
  { word: '강', category: 'NATURE' },
  { word: '호수', category: 'NATURE' },
  { word: '바다', category: 'NATURE' },
  { word: '섬', category: 'NATURE' },
  { word: '산', category: 'NATURE' },
  { word: '숲', category: 'NATURE' },
  { word: '초원', category: 'NATURE' },
  { word: '꽃', category: 'NATURE' },
  { word: '나무', category: 'NATURE' },
  { word: '잎', category: 'NATURE' },
  { word: '씨앗', category: 'NATURE' },
  { word: '선인장', category: 'NATURE' },
  { word: '대나무', category: 'NATURE' },
  { word: '해바라기', category: 'NATURE' },
  { word: '장미', category: 'NATURE' },
  { word: '튤립', category: 'NATURE' },
  { word: '해', category: 'NATURE' },
  { word: '달', category: 'NATURE' },
  { word: '별', category: 'NATURE' },
  { word: '은하수', category: 'NATURE' },
  { word: '혜성', category: 'NATURE' },
  { word: '바람', category: 'NATURE' },
  { word: '비', category: 'NATURE' },
  { word: '안개', category: 'NATURE' },
  { word: '서리', category: 'NATURE' },
  { word: '이슬', category: 'NATURE' },
  { word: '진흙', category: 'NATURE' },
  { word: '모래', category: 'NATURE' },
  { word: '바위', category: 'NATURE' },
  { word: '동굴', category: 'NATURE' },
  { word: '절벽', category: 'NATURE' },
  { word: '계곡', category: 'NATURE' },
  { word: '늪', category: 'NATURE' },
  { word: '버섯', category: 'NATURE' },
  { word: '포도나무', category: 'NATURE' },
  { word: '야자수', category: 'NATURE' },

  // PLACE (50)
  { word: '학교', category: 'PLACE' },
  { word: '병원', category: 'PLACE' },
  { word: '놀이공원', category: 'PLACE' },
  { word: '등대', category: 'PLACE' },
  { word: '공항', category: 'PLACE' },
  { word: '도서관', category: 'PLACE' },
  { word: '박물관', category: 'PLACE' },
  { word: '미술관', category: 'PLACE' },
  { word: '영화관', category: 'PLACE' },
  { word: '극장', category: 'PLACE' },
  { word: '공원', category: 'PLACE' },
  { word: '동물원', category: 'PLACE' },
  { word: '수족관', category: 'PLACE' },
  { word: '마트', category: 'PLACE' },
  { word: '편의점', category: 'PLACE' },
  { word: '식당', category: 'PLACE' },
  { word: '카페', category: 'PLACE' },
  { word: '빵집', category: 'PLACE' },
  { word: '약국', category: 'PLACE' },
  { word: '우체국', category: 'PLACE' },
  { word: '은행', category: 'PLACE' },
  { word: '경찰서', category: 'PLACE' },
  { word: '소방서', category: 'PLACE' },
  { word: '교회', category: 'PLACE' },
  { word: '절', category: 'PLACE' },
  { word: '성당', category: 'PLACE' },
  { word: '궁전', category: 'PLACE' },
  { word: '성', category: 'PLACE' },
  { word: '피라미드', category: 'PLACE' },
  { word: '항구', category: 'PLACE' },
  { word: '기차역', category: 'PLACE' },
  { word: '지하철역', category: 'PLACE' },
  { word: '버스터미널', category: 'PLACE' },
  { word: '주유소', category: 'PLACE' },
  { word: '주차장', category: 'PLACE' },
  { word: '수영장', category: 'PLACE' },
  { word: '체육관', category: 'PLACE' },
  { word: '볼링장', category: 'PLACE' },
  { word: '노래방', category: 'PLACE' },
  { word: '찜질방', category: 'PLACE' },
  { word: '캠핑장', category: 'PLACE' },
  { word: '해수욕장', category: 'PLACE' },
  { word: '스키장', category: 'PLACE' },
  { word: '놀이터', category: 'PLACE' },
  { word: '유치원', category: 'PLACE' },
  { word: '회사', category: 'PLACE' },
  { word: '공장', category: 'PLACE' },
  { word: '농장', category: 'PLACE' },
  { word: '온실', category: 'PLACE' },
  { word: '온천', category: 'PLACE' },

  // ACTION (50)
  { word: '달리기', category: 'ACTION' },
  { word: '점프', category: 'ACTION' },
  { word: '수영', category: 'ACTION' },
  { word: '박수', category: 'ACTION' },
  { word: '하품', category: 'ACTION' },
  { word: '잠자기', category: 'ACTION' },
  { word: '먹기', category: 'ACTION' },
  { word: '마시기', category: 'ACTION' },
  { word: '읽기', category: 'ACTION' },
  { word: '쓰기', category: 'ACTION' },
  { word: '그리기', category: 'ACTION' },
  { word: '노래', category: 'ACTION' },
  { word: '춤추기', category: 'ACTION' },
  { word: '울기', category: 'ACTION' },
  { word: '웃기', category: 'ACTION' },
  { word: '뛰기', category: 'ACTION' },
  { word: '걷기', category: 'ACTION' },
  { word: '오르기', category: 'ACTION' },
  { word: '내려가기', category: 'ACTION' },
  { word: '던지기', category: 'ACTION' },
  { word: '잡기', category: 'ACTION' },
  { word: '차기', category: 'ACTION' },
  { word: '밀기', category: 'ACTION' },
  { word: '당기기', category: 'ACTION' },
  { word: '들기', category: 'ACTION' },
  { word: '자르기', category: 'ACTION' },
  { word: '붙이기', category: 'ACTION' },
  { word: '열기', category: 'ACTION' },
  { word: '닫기', category: 'ACTION' },
  { word: '줄넘기', category: 'ACTION' },
  { word: '자전거타기', category: 'ACTION' },
  { word: '낚시', category: 'ACTION' },
  { word: '등산', category: 'ACTION' },
  { word: '스키타기', category: 'ACTION' },
  { word: '스케이트타기', category: 'ACTION' },
  { word: '권투', category: 'ACTION' },
  { word: '태권도', category: 'ACTION' },
  { word: '요가', category: 'ACTION' },
  { word: '명상', category: 'ACTION' },
  { word: '사진찍기', category: 'ACTION' },
  { word: '운전', category: 'ACTION' },
  { word: '요리', category: 'ACTION' },
  { word: '청소', category: 'ACTION' },
  { word: '빨래', category: 'ACTION' },
  { word: '쇼핑', category: 'ACTION' },
  { word: '포옹', category: 'ACTION' },
  { word: '악수', category: 'ACTION' },
  { word: '큰절', category: 'ACTION' },
  { word: '손흔들기', category: 'ACTION' },
  { word: '눈감기', category: 'ACTION' },

  // JOB (50)
  { word: '의사', category: 'JOB' },
  { word: '소방관', category: 'JOB' },
  { word: '요리사', category: 'JOB' },
  { word: '가수', category: 'JOB' },
  { word: '경찰', category: 'JOB' },
  { word: '선생님', category: 'JOB' },
  { word: '간호사', category: 'JOB' },
  { word: '군인', category: 'JOB' },
  { word: '농부', category: 'JOB' },
  { word: '어부', category: 'JOB' },
  { word: '화가', category: 'JOB' },
  { word: '음악가', category: 'JOB' },
  { word: '배우', category: 'JOB' },
  { word: '작가', category: 'JOB' },
  { word: '기자', category: 'JOB' },
  { word: '변호사', category: 'JOB' },
  { word: '판사', category: 'JOB' },
  { word: '건축가', category: 'JOB' },
  { word: '엔지니어', category: 'JOB' },
  { word: '과학자', category: 'JOB' },
  { word: '우주비행사', category: 'JOB' },
  { word: '파일럿', category: 'JOB' },
  { word: '선원', category: 'JOB' },
  { word: '버스기사', category: 'JOB' },
  { word: '택시기사', category: 'JOB' },
  { word: '미용사', category: 'JOB' },
  { word: '약사', category: 'JOB' },
  { word: '치과의사', category: 'JOB' },
  { word: '수의사', category: 'JOB' },
  { word: '사진사', category: 'JOB' },
  { word: '디자이너', category: 'JOB' },
  { word: '프로그래머', category: 'JOB' },
  { word: '회계사', category: 'JOB' },
  { word: '은행원', category: 'JOB' },
  { word: '우체부', category: 'JOB' },
  { word: '청소부', category: 'JOB' },
  { word: '경비원', category: 'JOB' },
  { word: '마술사', category: 'JOB' },
  { word: '서커스단원', category: 'JOB' },
  { word: '유튜버', category: 'JOB' },
  { word: '스트리머', category: 'JOB' },
  { word: '앵커', category: 'JOB' },
  { word: '코미디언', category: 'JOB' },
  { word: '연구원', category: 'JOB' },
  { word: '탐험가', category: 'JOB' },
  { word: '조종사', category: 'JOB' },
  { word: '심판', category: 'JOB' },
  { word: '코치', category: 'JOB' },
  { word: '트레이너', category: 'JOB' },
  { word: '웨이터', category: 'JOB' },
];

async function main() {
  const data = words.map(({ word, category }) => ({
    word,
    category,
    length: word.length,
  }));

  const result = await prisma.wordPool.createMany({
    data,
    skipDuplicates: true,
  });

  console.log(`Seeded ${result.count} words into WordPool`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
